// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ytmvwggshtrgvqfqngva.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl0bXZ3Z2dzaHRyZ3ZxZnFuZ3ZhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzIxMzQzODAsImV4cCI6MjA4NzcxMDM4MH0.3TA14qCxJdcByiKjk7jricyv-_eXO9h_Qlv6oCIRR9E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});